# Generated by Django 4.1.7 on 2023-09-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0004_lead_delete_ship"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("pincodes", models.TextField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
        ),
    ]
