# Generated by Django 4.1.7 on 2023-09-02 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0005_city"),
    ]

    operations = [
        migrations.DeleteModel(
            name="City",
        ),
    ]
